#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "Must be run as root.  Correct Usage sudo install_ball_plate"
	exit 1
fi

CWD=$(pwd)

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' gcc|grep "install ok installed")
echo Checking for gcc: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing gcc package"
	sudo apt-get --force-yes --yes install gcc
fi

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' alsa-utils|grep "install ok installed")
echo Checking for alsa-utils: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing alsa-utils package"
	sudo apt-get --force-yes --yes install alsa-utils
fi

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' evtest|grep "install ok installed")
echo Checking for evtest: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing evtest package"
	sudo apt-get --force-yes --yes install evtest
fi


PKG_OK=$(dpkg-query -W --showformat='${Status}\n' libcwiid1|grep "install ok installed")
echo Checking for libcwiid1: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing libcwiid1 package"
	sudo apt-get --force-yes --yes install libcwiid1
fi

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' libcwiid-dev|grep "install ok installed")
echo Checking for libcwiid-dev: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing libcwiid-dev package"
	sudo apt-get --force-yes --yes install libcwiid-dev
fi

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' make|grep "install ok installed")
echo Checking for make: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing make package"
	sudo apt-get --force-yes --yes install make
fi

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' bluez-utils|grep "install ok installed")
echo Checking for bluez-utils: $PKG_OK
if [ "" == "$PKG_OK" ]; then
	echo "Installing bluezutils package"
	sudo apt-get --force-yes --yes install bluez-utils
fi

if [ ! -d "/usr/share/sounds" ]; then
  echo "Creating /usr/share/sounds to save program *.wav files"
  mkdir /usr/share/sounds
fi

if [ ! -d "/usr/share/sounds/ball_plate" ]; then
  echo "Creating /usr/share/sounds/ball_plate to save program *.wav files"
  mkdir /usr/share/sounds/ball_plate
fi

cd /usr/share/sounds/ball_plate

if [ ! -f "bodyjar.wav" ]; then
	echo "Downloading bodyjar.wav"
	wget https://www.dropbox.com/sh/ig8wp31wmiojqgc/ip22MLCbwE/bodyjar.wav
fi

if [ ! -f "manual_start.wav" ]; then
	echo "Downloading manual_start.wav"
	wget https://www.dropbox.com/sh/ig8wp31wmiojqgc/ojPRoOcx-Z/manual_start.wav
fi

if [ ! -f "pair_remote.wav" ]; then
	echo "Downloading Pair_Remote.wav"
	wget https://www.dropbox.com/sh/ig8wp31wmiojqgc/uC36VzpmSy/pair_remote.wav
fi


cd "$CWD"
sudo cp 69-touchscreen.rules /etc/udev/rules.d


cd ..
make



